(global-set-key [f2] 'save-buffer)
(global-set-key [f3] 'find-file)
(global-set-key [C-f4] 'kill-this-buffer)
(global-set-key [f6] 'other-window)
(global-set-key [f9] 'compile)
(global-set-key [f11] 'delete-other-windows)
(global-set-key [f12] 'ff-find-other-file)

(global-set-key (kbd "C-j") 'switch-to-buffer)
(global-set-key (kbd "RET") 'newline-and-indent)
